name: Build UDX710 Tools
on:
  push:
  workflow_dispatch:
jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get update
          sudo apt-get install -y nodejs file

      - name: Cache cross compiler (aarch64)
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/tools/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu
          key: gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu

      - name: Configure cross compiler (aarch64)
        run: |
          mkdir -p $GITHUB_WORKSPACE/tools
          if [ ! -d "$GITHUB_WORKSPACE/tools/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu" ]; then
            cd $GITHUB_WORKSPACE/tools
            # 南阳理工大学 Linaro 镜像
            wget --no-verbose https://mirror.nyist.edu.cn/linaro-toolchain/binaries/7.5-2019.12/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
            if ! file gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz | grep -q "XZ compressed data"; then
              echo "ERROR: Downloaded file is not a valid tar.xz!"
              exit 1
            fi
            tar -xJf gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz
          fi
          echo "PATH=$PATH:$GITHUB_WORKSPACE/tools/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin" >> $GITHUB_ENV

      - name: build web
        run: |
          cd web
          npm install && npm run build

      - name: build server
        run: |
          cd src
          which aarch64-linux-gnu-gcc
          aarch64-linux-gnu-gcc --version
          make

      - name: dopack
        run: |
          mkdir -p output/6677
          echo "#!/bin/sh" > start.sh
          echo "cd /home/root/6677" >> start.sh
          echo "chmod 755 *" >> start.sh
          echo "./server &" >> start.sh
          mv start.sh output/6677/
          cp -r web/dist output/6677/
          cp src/build/ofono-server output/6677/server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: udx710-tools
          path: output
