name: Build UDX710 Tools
on:
  push:
  workflow_dispatch:
jobs:
  build-arm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies & aarch64 cross gcc
        run: |
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get update
          # Ubuntu22.04(jammy)源存在gcc7交叉编译器
          sudo apt-get install -y nodejs gcc-7-aarch64-linux-gnu g++-7-aarch64-linux-gnu file

      - name: build web
        run: |
          cd web
          npm install && npm run build

      - name: build server
        run: |
          cd src
          # 打印调试信息确认编译器
          which aarch64-linux-gnu-gcc-7
          aarch64-linux-gnu-gcc-7 --version
          # 如果Makefile默认用aarch64-linux-gnu-gcc，需要指定CC
          make CC=aarch64-linux-gnu-gcc-7 CXX=aarch64-linux-gnu-g++-7

      - name: dopack
        run: |
          mkdir -p output/6677
          echo "#!/bin/sh" > start.sh
          echo "cd /home/root/6677" >> start.sh
          echo "chmod 755 *" >> start.sh
          echo "./server &" >> start.sh
          mv start.sh output/6677/
          cp -r web/dist output/6677/
          cp src/build/ofono-server output/6677/server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: udx710-tools
          path: output
